### ISSUE TITLE
Refrect.js an zone.js are pointing to a wrong endpoint in index.html

### ISSUE THREAD

**Issue by marchitos** [pkozlowski-opensource/ng2-webpack-play#2]
Reflect.js an zone.js are pointing to a wrong endpoint in index.html
I suppose the correct paths are

/node_modules/reflect-metadata/Reflect.js
/node_modules/zone.js/dist/zone.js

instead of 

/node_modules/angular2/node_modules/reflect-metadata/Reflect.js
/node_modules/angular2/node_modules/zone.js/dist/zone.js

**Comment by Foxandxss** [comment]
No, they are correct. He is reusing the zone.js and reflect.js that lives inside angular 2. Not installing an external one

**Comment by pkozlowski-opensource** [comment]
Yeh, I want to make sure that the project uses the exact same versions of deps that angular2 was built with. 

The only thing that comes to my mind is npm version - afaik 3.x de-dupes deps so it might change folders. @marchitos what it your npm version?

**Comment by Zyzle** [comment]
@pkozlowski-opensource Hmmn, I was actually about to submit a PR for this, looks like you're right, I'm using npm 3.3.6 here and there is no `node_modules` inside the `node_modules/angular2` directory with a fresh clone + `npm install`

**Comment by pkozlowski-opensource** [comment]
With alpha.47 we've got "external dependencies" bundle inside ng2 distribution so don't need to sneak into ng2 dependencies any more. See 2289a26d28b5d5903364f704d068c0a444cc74af for the details.

Closing as 2289a26d28b5d5903364f704d068c0a444cc74af solves this one.
